# Generated by Django 5.0.4 on 2024-05-23 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Territorios',
            fields=[
                ('id_territorio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_territorio', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id_visita', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_capitan', models.CharField(max_length=50)),
                ('fecha_visita', models.DateField()),
                ('fecha_registro', models.DateField()),
                ('estado_visita', models.BooleanField(default=False)),
                ('territorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territorios.territorios')),
            ],
        ),
    ]
